// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmevhbhhizayxdfivlpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZXZoYmhoaXpheXhkZml2bHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDU2NzEsImV4cCI6MjA1OTI4MTY3MX0.rcG2rwLRmh9KhxaYKqrT7_FU_i-P6quEookhhSO8r6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);